# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='post_local_cohesion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textdata',
            name='pre_local_cohesion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
