# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0003_measurement_instruction_strategies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveLoadRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.PositiveSmallIntegerField()),
                ('question2', models.PositiveSmallIntegerField()),
                ('question3', models.PositiveSmallIntegerField()),
                ('question4', models.PositiveSmallIntegerField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohapp.Experiment', verbose_name=b'Experiment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohapp.Subject', verbose_name=b'Subject')),
            ],
        ),
    ]
