# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0004_cognitiveloadrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitiveloadrevision',
            name='measurement',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
