# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0006_cognitiveloaddraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cognitiveloaddraft',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='cognitiveloaddraft',
            name='subject',
        ),
        migrations.AddField(
            model_name='textdata',
            name='cld_draft_question1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='cld_draft_question2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='cld_draft_question3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='cld_draft_question4',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CognitiveLoadDraft',
        ),
    ]
