# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0007_auto_20170825_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cognitiveloadrevision',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='cognitiveloadrevision',
            name='subject',
        ),
        migrations.AddField(
            model_name='textdata',
            name='cld_revision_question1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='cld_revision_question2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='cld_revision_question3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='cld_revision_question4',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CognitiveLoadRevision',
        ),
    ]
