# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0009_auto_20171013_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='template',
        ),
    ]
