# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0010_remove_group_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='cld_middle_question1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='cld_middle_question2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='cld_middle_question3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='cld_middle_question4',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
