# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0011_auto_20171013_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdata',
            name='cld_middle_question1',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='cld_middle_question2',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='cld_middle_question3',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='cld_middle_question4',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
