# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0013_auto_20171124_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='accuracy_revision_global',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='accuracy_revision_local',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
