# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0014_auto_20171124_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdata',
            name='cld_draft_question3',
        ),
        migrations.RemoveField(
            model_name='textdata',
            name='cld_middle_question3',
        ),
        migrations.RemoveField(
            model_name='textdata',
            name='cld_revision_question3',
        ),
    ]
