# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-04-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0015_auto_20171130_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='g06fu1fb',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='g07fu2fb',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='g10fu5fb',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='g8fu3fb',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='g9fu4fb',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
