# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-04-09 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0016_auto_20200409_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='g11eda5',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='g12eda6',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='g13eda7',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='g14eda8',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
