# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-05-07 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohapp', '0017_auto_20200409_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='emo1_draft',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='emo2_draft',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='emo3_draft',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textdata',
            name='emo4_draft',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
